[build]
  base = "."
  command = "cd client && pnpm install && pnpm run build"
  publish = "client/dist"

[context.production]
  command = "cd client && pnpm install && pnpm run build"

[context.deploy-preview]
  command = "cd client && pnpm install && pnpm run build"
