[build]
  base = "client"
  command = "pnpm install && pnpm run build"
  publish = "dist"

[context.production]
  command = "pnpm install && pnpm run build"

[context.deploy-preview]
  command = "pnpm install && pnpm run build"
